name: 'IssueLabeler - Predictor'
description: 'A GitHub Action issue labeler that predicts a label based on a machine-learning model trained against existing issues or pull requests.'

branding:
  icon: tag
  color: purple

inputs:
  model_path:
    description: 'The path to the prediction model file, typically restored using actions/cache/restore.'
    required: true
  issue_numbers:
    description: 'The issue numbers to predict labels for. A comma-separated list of numbers or number ranges.'

runs:
  using: docker
  image: docker://ghcr.io/jeffhandley/dotnet-action/predictor:main
