name: 'Issue Labeler - Predict Issues'

on:
  workflow_dispatch:
    inputs:
      predictor-version:
        required: true

      numbers:
        required: true

jobs:
  predict:
    name: 'Predict Labels'
    runs-on: ubuntu-latest

    steps:
      - name: 'Run Predictor'
        uses: jeffhandley/dotnet-action/predictor@main
        id: run-predictor
        with:
          version: ${{ inputs.predictor-version }}
          issue-numbers: ${{ inputs.numbers }}
