name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

  release:
    types: [published]

env:
  PREDICTOR_IMAGE_NAME: jeffhandley/dotnet-action/predictor
  BASE_IMAGE: mcr.microsoft.com/dotnet/nightly/runtime-deps:8.0-jammy-chiseled-aot

jobs:
  publish-predictor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.22

      - name: Get the version from the release
        if: github.event_name == 'release'
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Get the version from the workflow inputs
        if: github.event_name == 'workflow_dispatch'
        run: echo "RELEASE_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Set up the .NET SDK
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 8.0.x

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Predictor App
        working-directory: ./src/IssueLabeler.Predictor
        run: |
          dotnet publish \
            /t:PublishContainer \
            -p DebugType=none \
            -p ContainerBaseImage=${{ env.BASE_IMAGE }} \
            -p ContainerRegistry=ghcr.io \
            -p ContainerImageTags='"${{ env.RELEASE_VERSION }}"' \
            -p ContainerRepository=${{ env.PREDICTOR_IMAGE_NAME }} \
            -bl

      - name: Upload binlog artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: msbuild.binlog
          path: ./src/IssueLabeler.Predictor/msbuild.binlog
